<?php
$smilies = array
    (
    ":)" => "smile.png",
    ":(" => "sad.png",
    ";)z" => "wink.png",
    ":P" => "razz.png",
    ":D" => "grin.png",
    ":|" => "plain.png",
    ":O" => "suprise.png",
    ":?" => "confused.png",
    "8)" => "glasses.png",
    "8o" => "eek.png",
    "B)" => "cool.png",
    ":-)" => "smile-big.png",
    ":-(" => "crying.png",
    ":-*" => "kiss.png",
    "O:-D" => "angel.png",
    ":-@" => "devilish.png",
    ":o)" => "monkey.png",
    ":help" => "help.png",
    ":love" => "love.png",
    ":warn" => "warn.png",
    ":bomb" => "bomb.png",
    ":idea" => "idea.png",
    ":bad" => "bad.png",
    ":!" => "important.png",
    "brb" => "brb.png",
    ":gigg" => "giggle.png",
    ":rofl" => "roflmao.png",
    ":slep" => "sleep.png",
    ":thum" => "thumbsup.png",
    ":0_0" => "zpo.png",
    ":poop" => "poop.png",
    ":spechles" => "speechless.png",
    ":unsure" => "unsure.png",
    ":mad" => "mad.png",
    ":roll" => "rolleyes.png",
    ":sick" => "sick.png",
    ":crylol" => "crylaugh.png",
    ":confos" => "confound.png",
    ":fire" => "fire.png",
);

$smilies1 = array
    (

	":angel:" => "emoticons/angel.png",
	":angry:" => "emoticons/angry.png",
	"8-)" => "emoticons/cool.png",
	":'(" => "emoticons/cwy.png",
	":ermm:" => "emoticons/ermm.png",
	"<3" => "emoticons/heart.png",
	":O" => "emoticons/shocked.png",
    ";)" => "emoticons/wink.png",
	":alien:" => "emoticons/alien.png",
	":blink:" => "emoticons/blink.png",
	":blush:" => "emoticons/blush.png",
	":cheerful:" => "emoticons/cheerful.png",
	":devil:" => "emoticons/devil.png",
	":dizzy:" => "emoticons/dizzy.png",
	":getlost:" => "emoticons/getlost.png",
	":happy:" => "emoticons/happy.png",
	":kissing:" => "emoticons/kissing.png",
	":ninja:" => "emoticons/ninja.png",
	":pinch:" => "emoticons/pinch.png",
	":pouty:" => "emoticons/pouty.png",
	":sick:" => "emoticons/sick.png",
	":sideways:" => "emoticons/sideways.png",
	":silly:" => "emoticons/silly.png",
	":sleeping:" => "emoticons/sleeping.png",
	":unsure:" => "emoticons/unsure.png",
	":woot:" => "emoticons/w00t.png",
	":wassat:" => "emoticons/wassat.png",
	":whistling:" => "emoticons/whistling.png",
	":love:" => "emoticons/wub.png",
	);
	/*
$smilies1 = array
    (
	":)" => "emoticons/smile.png",
	":angel:" => "emoticons/angel.png",
	":angry:" => "emoticons/angry.png",
	"8-)" => "emoticons/cool.png",
	":'(" => "emoticons/cwy.png",
	":ermm:" => "emoticons/ermm.png",
	":D" => "emoticons/grin.png",
	"<3" => "emoticons/heart.png",
	":(" => "emoticons/sad.png",
	":O" => "emoticons/shocked.png",
	":P" => "emoticons/tongue.png",
	";)" => "emoticons/wink.png",
	":alien:" => "emoticons/alien.png",
	":blink:" => "emoticons/blink.png",
	":blush:" => "emoticons/blush.png",
	":cheerful:" => "emoticons/cheerful.png",
	":devil:" => "emoticons/devil.png",
	":dizzy:" => "emoticons/dizzy.png",
	":getlost:" => "emoticons/getlost.png",
	":happy:" => "emoticons/happy.png",
	":kissing:" => "emoticons/kissing.png",
	":ninja:" => "emoticons/ninja.png",
	":pinch:" => "emoticons/pinch.png",
	":pouty:" => "emoticons/pouty.png",
	":sick:" => "emoticons/sick.png",
	":sideways:" => "emoticons/sideways.png",
	":silly:" => "emoticons/silly.png",
	":sleeping:" => "emoticons/sleeping.png",
	":unsure:" => "emoticons/unsure.png",
	":woot:" => "emoticons/w00t.png",
	":wassat:" => "emoticons/wassat.png",
	":whistling:" => "emoticons/whistling.png",
	":love:" => "emoticons/wub.png",
	);
	*/