<br>
<div class="border border-primary">
    <ul class="list-group">
    <li class="list-group-item"><a href="<?php echo TTURL; ?>/admincp?action=adduser"><img src="<?php echo TTURL; ?>/images/admin/adduser.png" border="0" width="20" height="20" alt="" />&nbsp;<b><?php echo T_("Add User"); ?></b></a></li>
    <li class="list-group-item"><a href="<?php echo TTURL; ?>/admincp?action=usersearch"><img src="<?php echo TTURL; ?>/images/admin/user_search.png" border="0" width="20" height="20" alt="" />&nbsp;<b><?php echo T_("ADVANCED_USER_SEARCH"); ?></b></a></li>
    <li class="list-group-item"><a href="<?php echo TTURL; ?>/admincp?action=avatars"><img src="<?php echo TTURL; ?>/images/admin/avatar_log.png" border="0" width="20" height="20" alt="" />&nbsp;<b><?php echo T_("AVATAR_LOG"); ?></b></a></li>
    <li class="list-group-item"><a href="<?php echo TTURL; ?>/admincp?action=backups"><img src="<?php echo TTURL; ?>/images/admin/db_backup.png" border="0" width="20" height="20" alt="" />&nbsp;<b><?php echo T_("BACKUPS"); ?></b></a></li>
    <li class="list-group-item"><a href="<?php echo TTURL; ?>/admincp?action=ipbans"><img src="<?php echo TTURL; ?>/images/admin/ip_block.png" border="0" width="20" height="20" alt="" />&nbsp;<b><?php echo T_("BANNED_IPS"); ?></b></a></li>
    <li class="list-group-item"><a href="<?php echo TTURL; ?>/admincp?action=bannedtorrents"><img src="<?php echo TTURL; ?>/images/admin/banned_torrents.png" border="0" width="20" height="20" alt="" />&nbsp;<b><?php echo T_("BANNED_TORRENTS"); ?></b></a></li>
    <li class="list-group-item"><a href="<?php echo TTURL; ?>/admincp?action=blocks&amp;do=view"><img src="<?php echo TTURL; ?>/images/admin/blocks.png" border="0" width="20" height="20" alt="" />&nbsp;<b><?php echo T_("BLOCKS"); ?></b></a></li>
    <li class="list-group-item"><a href="<?php echo TTURL; ?>/client"><img src="<?php echo TTURL; ?>/images/admin/client.png" border="0" width="20" height="20" alt="" />&nbsp;<b>Client Ban</b></b></a></li>
    <li class="list-group-item"><a href="<?php echo TTURL; ?>/admincp?action=cheats"><img src="<?php echo TTURL; ?>/images/admin/cheats.png" border="0" width="20" height="20" alt="" />&nbsp;<b><?php echo T_("Detect Cheats"); ?></b></a></li>
    <li class="list-group-item"><a href="<?php echo TTURL; ?>/admincp?action=duplicateips"><img src="<?php echo TTURL; ?>/images/admin/double-ip.ico" border="0" width="20" height="20" alt="" />&nbsp;<b><?php echo T_("DUPLICATEIP"); ?></b></a></li> 
    <li class="list-group-item"><a href="<?php echo TTURL; ?>/admincp?action=emailbans"><img src="<?php echo TTURL; ?>/images/admin/mail_bans.png" border="0" width="20" height="20" alt="" />&nbsp;<b><?php echo T_("EMAIL_BANS"); ?></b></a></li>
    <li class="list-group-item"><a href="<?php echo TTURL; ?>/faq/manage"><img src="<?php echo TTURL; ?>/images/admin/faq.png" border="0" width="20" height="20" alt="" />&nbsp;<b><?php echo T_("FAQ"); ?></b></a></li>
    <li class="list-group-item"><a href="<?php echo TTURL; ?>/admincp?action=forum"><img src="<?php echo TTURL; ?>/images/admin/forums.png" border="0" width="20" height="20" alt="" />&nbsp;<b><?php echo T_("FORUM_MANAGEMENT"); ?></b></a></li>
	<li class="list-group-item"><a href="<?php echo TTURL; ?>/admincp?action=freetorrents"><img src="<?php echo TTURL; ?>/images/admin/free_leech.png" border="0" width="20" height="20" alt="" />&nbsp;<b>Freeleech Torrents</b></a></li>
    <li class="list-group-item"><a href="<?php echo TTURL; ?>/admincp?action=hnr"><img src="<?php echo TTURL; ?>/images/hitnrun.png" border="0" width="20" height="20" alt="" />&nbsp;<b>Hit & Runs</b></a></li>
    <li class="list-group-item"><a href="<?php echo TTURL; ?>/admincp?action=lastcomm"><img src="images/admin/comments.png" border="0" width="20" height="20" alt="" />&nbsp;<b><?php echo T_("LATEST_COMMENTS"); ?></b></a></li>
    <li class="list-group-item"><a href="<?php echo TTURL; ?>/admincp?action=masspm"><img src="<?php echo TTURL; ?>/images/admin/mass_pm.png" border="0" width="20" height="20" alt="" />&nbsp;<b><?php echo T_("MASS_PM"); ?></b></a></li>
    <li class="list-group-item"><a href="<?php echo TTURL; ?>/admincp?action=messagespy"><img src="<?php echo TTURL; ?>/images/admin/message_spy.png" border="0" width="20" height="20" alt="" />&nbsp;<b><?php echo T_("MESSAGE_SPY"); ?></b></a></li>
    <li class="list-group-item"><a href="<?php echo TTURL; ?>/admincp?action=news&amp;do=view"><img src="<?php echo TTURL; ?>/images/admin/news.png" border="0" width="20" height="20" alt="" />&nbsp;<b><?php echo T_("NEWS"); ?></b></a></li>
    <li class="list-group-item"><a href="<?php echo TTURL; ?>/admincp?action=peers"><img src="<?php echo TTURL; ?>/images/admin/peer_list.png" border="0" width="20" height="20" alt="" />&nbsp;<b><?php echo T_("PEERS_LIST"); ?></b></a></li>
    <li class="list-group-item"><a href="<?php echo TTURL; ?>/admincp?action=invited"><img src="<?php echo TTURL; ?>/images/admin/invited_user.png" border="0" width="20" height="20" alt="" />&nbsp;<b>Invited Users</b></a></li>   
    </ul>
</div>