<br>
<div class="border border-primary"> 
    <ul class="list-group">
    <li class="list-group-item"><a href="<?php echo TTURL; ?>/admincp?action=privacylevel"><img src="<?php echo TTURL; ?>/images/admin/privacy_level.png" border="0" width="20" height="20" alt="" />&nbsp;<b>Privacy Level</b></a></li>    
    <li class="list-group-item"><a href="<?php echo TTURL; ?>/admincp?action=pendinginvite"><img src="<?php echo TTURL; ?>/images/admin/pending_invited_user.png" border="0" width="20" height="20" alt="" />&nbsp;<b>Pending Invited Users</b></b></a></li>
    <li class="list-group-item"><a href="<?php echo TTURL; ?>/admincp?action=polls&amp;do=view"><img src="<?php echo TTURL; ?>/images/admin/polls.png" border="0" width="20" height="20" alt="" />&nbsp;<b><?php echo T_("POLLS"); ?></b></a></li>
    <li class="list-group-item"><a href="<?php echo TTURL; ?>/admincp?action=reports&amp;do=view"><img src="<?php echo TTURL; ?>/images/admin/report_system.png" border="0" width="20" height="20" alt="" />&nbsp;<b><?php echo T_("REPORTS"); ?></b></a></li>
    <li class="list-group-item"><a href="<?php echo TTURL; ?>/admincp?action=rules&amp;do=view"><img src="<?php echo TTURL; ?>/images/admin/rules.png" border="0" width="20" height="20" alt="" />&nbsp;<b><?php echo T_("RULES"); ?></b></a></li>
    <li class="list-group-item"><a href="<?php echo TTURL; ?>/admincp?action=seedbonus"><img src="<?php echo TTURL; ?>/images/admin/seedbonus.png" border="0" width="20" height="20" alt="" />&nbsp;<b>Seed Bonus</b></a></li>
    <li class="list-group-item"><a href="<?php echo TTURL; ?>/admincp?action=sitelog"><img src="<?php echo TTURL; ?>/images/admin/site_log.png" border="0" width="20" height="20" alt="" />&nbsp;<b><?php echo T_("SITELOG"); ?></b></a></li>
    <li class="list-group-item"><a href="<?php echo TTURL; ?>/admincp?action=users"><img src="<?php echo TTURL; ?>/images/admin/simple_user_search.png" border="0" width="20" height="20" alt="" />&nbsp;<b>Simple User Search</b></a></li> 
    <li class="list-group-item"><a href="<?php echo TTURL; ?>/contactstaff/staffbox"><img src="<?php echo TTURL; ?>/images/admin/staffmess.png" border="0" width="20" height="20" alt="" />&nbsp;<b>Staff Messages</b></b></a></li>
    <li class="list-group-item"><a href="<?php echo TTURL; ?>/exceptions/admin"><img src="<?php echo TTURL; ?>/images/admin/sql_error.png" border="0" width="20" height="20" alt="" />&nbsp;<b>SQL Error</b></a></li> 
    <li class="list-group-item"><a href="<?php echo TTURL; ?>/teams/create"><img src="<?php echo TTURL; ?>/images/admin/teams.png" border="0" width="20" height="20" alt="" />&nbsp;<b><?php echo T_("TEAMS"); ?></b></a></li>
    <li class="list-group-item"><a href="<?php echo TTURL; ?>/admincp?action=style"><img src="<?php echo TTURL; ?>/images/admin/themes.png" border="0" width="20" height="20" alt="" />&nbsp;<b><?php echo T_("THEME_MANAGEMENT"); ?></b></a></li>
    <li class="list-group-item"><a href="<?php echo TTURL; ?>/admincp?action=categories&amp;do=view"><img src="<?php echo TTURL; ?>/images/admin/torrent_cats.png" border="0" width="20" height="20" alt="" />&nbsp;<b><?php echo T_("TORRENT_CAT_VIEW"); ?></b></a></li>
    <li class="list-group-item"><a href="<?php echo TTURL; ?>/admincp?action=torrentlangs&amp;do=view"><img src="<?php echo TTURL; ?>/images/admin/torrent_lang.png" border="0" width="20" height="20" alt="" />&nbsp;<b><?php echo T_("TORRENT_LANG"); ?></b></a></li>
    <li class="list-group-item"><a href="<?php echo TTURL; ?>/admincp?action=torrentmanage"><img src="<?php echo TTURL; ?>/images/admin/torrents.png" border="0" width="20" height="20" alt="" />&nbsp;<b><?php echo T_("TORRENTS"); ?></b></a></li>
    <li class="list-group-item"><a href="<?php echo TTURL; ?>/admincp?action=groups&amp;do=view"><img src="<?php echo TTURL; ?>/images/admin/user_groups.png" border="0" width="20" height="20" alt="" />&nbsp;<b><?php echo T_("USER_GROUPS_VIEW"); ?></b></a></li>
    <li class="list-group-item"><a href="<?php echo TTURL; ?>/admincp?action=warned"><img src="<?php echo TTURL; ?>/images/admin/warned_user.png" border="0" width="20" height="20" alt="" />&nbsp;<b><?php echo T_("WARNED_USERS"); ?></b></a></li>
    <li class="list-group-item"><a href="<?php echo TTURL; ?>/admincp?action=whoswhere"><img src="<?php echo TTURL; ?>/images/admin/whos_where.png" border="0" width="20" height="20" alt="" />&nbsp;<b><?php echo T_("WHOS_WHERE"); ?></b></a></li>
    <li class="list-group-item"><a href="<?php echo TTURL; ?>/admincp?action=censor"><img src="<?php echo TTURL; ?>/images/admin/word_censor.png" border="0" width="20" height="20" alt="" />&nbsp;<b><?php echo T_("WORD_CENSOR"); ?></b></a></li>
    <li class="list-group-item"><a href="<?php echo TTURL; ?>/admincp?action=clearshout"><img src="<?php echo TTURL; ?>/images/shoutclear.png" border="0" width="20" height="20" alt="" />&nbsp;<b><?php echo T_("CLEAR_SHOUTBOX"); ?></b></a></li>
    </ul>
</div>